spring.application.name=GPUaaS-b

spring.security.user.name=admin
spring.security.user.password=admin

# JPA Configuration
spring.datasource.url=jdbc:postgresql://localhost:52945/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Logging configuration
logging.level.root=INFO
logging.level.com.funa=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO

# Enable request logging
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.display-request-duration=true
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json
# ??????? "/api-docs(JSON)"? ??? ? ??? ??? ??? ??.
server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# Redis Configuration (for Redis Streams)
spring.data.redis.host=localhost
spring.data.redis.port=6379